### ISSUE TITLE
Dekker feedback

### ISSUE THREAD

**Issue by simultech** [deco3500/TheLocalCode#1]
Social community news platform within schools is quite interesting, chat to Feh about what is already out there.  What age group are you focusing on?  Focus on what makes the school context unique.  Have a look at nnub (community based notice boards).

**Comment by davo27** [comment]
We are focusing on high school students (from ages 12 to 18 year old students depending on state). We've looked at a few different nnub's out there. Facebook again seems like a popular virtual location to have this one. The issue with schools is that they have no control over what students view, parents may not like their kids having Facebook, and it has a lot of features which could be disruptive to their school environment (i.e. chat features). Kids will use it in likelihood, but it doesn't need to be encouraged by the school. 

We shall continue to look at what makes this context unique.
