### ISSUE TITLE
Demo AR SDK of choice

### ISSUE THREAD

**Issue by farahidahanim** [deco3500/TheLocalCode#21]
# ** Description **
Before we can implemented actually interactive digital prototype we need a better understanding of the frameworks and how to implemented them. Therefore we need a demo prototype showing off AR features in the real world.

# **Dependencies **
- we need to determine platform of prototype before we proceed.
- knowledge of AR research, developing skills.

# **CheckList**
- [x] AR SDK implement
- [x] Functions on platofrm of choice
- [x] resembles AR notice board
- [x] uplaoded and documented on GitHub.

**Comment by davo27** [comment]
No longer important due to changes in concept, AR no long as important
