### ISSUE TITLE
Create Personas

### ISSUE THREAD

**Issue by farahidahanim** [deco3500/TheLocalCode#25]
since we have  new features for the prototypes. we need  persona that has  needs and goals that fulfill the features. 

- [x] who have interested with the debate issue 

- [x] student who want to play games e.g chess. 

- [x] student who want to keep updated with school news and activities

**Comment by davo27** [comment]
Personas all created and found on the google drive

**Comment by davo27** [comment]
![persona1-deco3500](https://cloud.githubusercontent.com/assets/13531826/19548969/33e41160-96ed-11e6-9e6b-f63c27e40402.jpg)
