### ISSUE TITLE
schemas and ERD 

### ISSUE THREAD

**Issue by farahidahanim** [deco3500/TheLocalCode#26]
Since we only focus on one type of user which is students. therefore, all the related model will determine base on student activity. 

- identify all related schemas for entities. 
- draw ERD to show the relationship between entities.

**Comment by farahidahanim** [comment]
[Schemas.pdf](https://github.com/deco3500/TheLocalCode/files/514995/Schemas.pdf)

this is completed ERD and schemas. 
i am not really sure about the entity for GAMES.

**Comment by farahidahanim** [comment]
[Schemas.pdf](https://github.com/deco3500/TheLocalCode/files/520557/Schemas.pdf)

updated schemas

**Comment by davo27** [comment]
They all look good. Have been added to a server demo.
