### ISSUE TITLE
Rhys McCane Feedback

### ISSUE THREAD

**Issue by rhysmakesthings** [deco3500/TheLocalCode#3]
The idea of sending newsletters directly to parents is really good, I remember my school newsletter had to be handed to the students and often I would forget to take it because it didn't interest me personally.

How do you promote student engagement? Since their parents and their teachers both have access to this and can read what happens the students will have to have a strong reason to use it as opposed to Facebook where they have more privacy.

If it gives the students some benefit other than just reading what's happening then they will be more inclined to use it. But maybe just using it as a platform for teacher/parent interaction is another way you could take your project as i think parents would find that very valuable.

**Comment by davo27** [comment]
Thanks for your feedback! Promoting student engagement is actually something we are really concerned about. Its something which is going to require more thought and research on. We are incorporating Augment Reality with it now as it has been suggest to us. We hope this might help promote student engagement.

Also we are considering removing the idea that parents can view what students add as to address your main concern.
