### ISSUE TITLE
Critique on thelocalcode

### ISSUE THREAD

**Issue by wongkaiwks** [deco3500/TheLocalCode#4]
I love the idea you try to build up the platform fpr the sutdents. But how can you make sure the information won't bring up the privacy issue. Since some detail may not able to publish for the users. You may want to deal up with this problem.  One more thing is the idea is interesting enough.  Keep go ahead working on this idea

**Comment by davo27** [comment]
So our idea was to make sure the system was completely enclosed in the school and that all student posts would be passed through the school body first before being circulated though out the school (by a range of teachers for example). This would help keep things safe and prevent privacy breeches. Anyone posting "bad" things will automatically be known to the school.

Thanks for the feedback :)
