### ISSUE TITLE
Proposal Critique

### ISSUE THREAD

**Issue by mtimmo** [deco3500/TheLocalCode#6]
Hey Guys,

Cool concept! I sort of wish I had this back at school. 

I didn't hear you request any particular feedback, but I'll still address a main concern of mine with some questions for thought regarding the immaturity of students.
* How will you filter our immature or inappropriate comments by students?
* This could also be used as a method of bullying, so really linking back to the question above.
* Is there privacy settings that mean some posts are only available to certain students (and hence hidden from the main bulletin boards)?

Good Luck!

**Comment by davo27** [comment]
Thanks for the feedback :)

1. so students posts need to be filtered through the teaching staff/admins of the board. The idea being its the staffs responsibility to filter our "bad things" and bullying.
2. See previous response (1.). Hopefully less Bullying than what occurs on Facebook, if any. Ideally this would be designed in a way to prevent bullying. 
3. Any horrible posts or just bad posts like that should be caught by staff. When they catch these posts they know who posts them and when, giving them control over the system and preventing this.

Cheers for the feedback :) They are common concerns so we will continue to keep them in mind.
