### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dean-l** [deco3500/TheLocalCode#8]
This is a really good idea and I think it could be very useful. it seems to me that the hardest part of this concept would be how to get teachers and students to use it. Think about an implementation strategy so that if it were to be launched, how do you motivate people to use it and not fall back to their less efficient ways?

**Comment by davo27** [comment]
Hi, thanks for the feedback :). This is actually something the team and I haven't really thought of so its really great to receive this feedback. This is something we will consider in future designs of the project.

I guess at this point however we would need to make this app more "attractive" to use than less efficient ways. But this is easier said than done. So we will continue researching.

Thanks for the feedback again!
